### ISSUE TITLE
Roadmap to version v0.1

### ISSUE THREAD

**Issue by hugomn** [hugomn/gatsby-starter-medium#1]
Listing here the main topics that need to be achieved before having the first version of our gatsbium theme. 

- [ ] Add medium typography
- [ ] Add medium design system
- [ ] Add main header
- [ ] Add i18n with gatsby-plugin-18n
- [ ] Add disquss
- [ ] Host starter in github pages and add CI
- [ ] Publish starter to gatsby directory
- [ ] Update README

**Comment by hugomn** [comment]
Features not required to version v0.1:

- [ ] Add i18n with gatsby-i18n-plugin

**Comment by gurpreet-hanjra** [comment]
Hello, about Add medium design system - are there any resources or documentation available?

**Comment by hugomn** [comment]
@gurpreet-hanjra not exactly. For the design system, I was thinking that we need to add a CSS library. I was strongly inclined to choose `styled components`. Do you have any thoughts on that?

After selecting the CSS library, the idea would be to create a simple `theme`, with Medium colors. We could also think about picking a UI library, so we could have easily customized UI components.

**Comment by gurpreet-hanjra** [comment]
That sounds great! styled components is good!

**Comment by hugomn** [comment]
That's done now. I added styled-components with a basic theme component. Created `Header` to test the design system.

**Comment by gurpreet-hanjra** [comment]
Hello, how about a new start :) Sorry I couldn't do much last time. How can we proceed with Medium design system, any pointers?

**Comment by hugomn** [comment]
Hey @gurpreet-hanjra 👋🏼. Are you still up for the challenge? I think we can  now evaluate moving it to a gatsby theme instead of a starter. Have you checked gatsby themes already?

**Comment by gurpreet-hanjra** [comment]
Yes, still up for the challenge 👍 I will check out gatsby themes.
